apiVersion: v1
kind: Namespace
metadata:
  name: b00929835

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: b00929835pvc
  namespace: b00929835
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: b00929835c1
  namespace: b00929835
spec:
  selector:
    app: b00929835c1
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000

---
apiVersion: v1
kind: Service
metadata:
  name: b00929835c2
  namespace: b00929835
spec:
  selector:
    app: b00929835c2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b00929835c1
  namespace: b00929835
spec:
  selector:
    matchLabels:
      app: b00929835c1
  replicas: 1
  template:
    metadata:
      labels:
        app: b00929835c1
    spec:
      containers:
        - name: b00929835c1
          image: northamerica-northeast1-docker.pkg.dev/k8b00929835/container1/conatiner1-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
          volumeMounts:
            - mountPath: /b00929835_PV_dir
              name: b00929835pvc
      volumes:
        - name: b00929835pvc
          persistentVolumeClaim:
            claimName: b00929835k8pvc

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: b00929835c2
  namespace: b00929835
spec:
  selector:
    matchLabels:
      app: b00929835c2
  replicas: 1
  template:
    metadata:
      labels:
        app: b00929835c2
    spec:
      containers:
        - name: b00929835c2
          image: northamerica-northeast1-docker.pkg.dev/k8b00929835/conatainer2/conatiner2-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /b00929835_PV_dir
              name: b00929835pvc
      volumes:
        - name: b00929835pvc
          persistentVolumeClaim:
            claimName: b00929835k8pvc
